### ISSUE TITLE
Cannot run this mod on the Server

### ISSUE THREAD

**Issue by Dr-ppp** [bioastroiner/gt6scan#1]
I get an error when I try to run this mod on the server,I found a reflection permission problem caused by a method that did not have public,After I modified it, it can run on the server, but when I actually tested it, I couldn't open the GUI interface on the server.My English is not good, I hope my description of this problem is not wrong.

**Comment by bioastroiner** [comment]
No problem, Can you explain what method did you edit and send a detailed
log of what happend.

**Comment by Dr-ppp** [comment]
In the commonproxy.java file, the CommonProxy() method can be run on the server side with the public modifier
[latest.log](https://github.com/bioastroiner/gt6scan/files/13853244/latest.log)

**Comment by bioastroiner** [comment]
> In the commonproxy.java file, the CommonProxy() method can be run on the server side with the public modifier [latest.log](https://github.com/bioastroiner/gt6scan/files/13853244/latest.log)

Fixed in the next Update, Reminder that ModularUI2 needs to be present on both Server and the Client, Also the Only ModularUI2 version acceptable for the new version is 2.0.8-1.7.10

**Comment by bioastroiner** [comment]
try this nightly build of the upcomming version
https://github.com/bioastroiner/gt6scan/actions/runs/7554658873/artifacts/1174875874

**Comment by ruananta** [comment]
I have a similar problem. It works in a single player game, but the server with this mod does not start.

**Comment by Dr-ppp** [comment]
> 我有一个类似的问题。它可以在单人游戏中运行，但是带有此模组的服务器无法启动。

等作者更新就好

**Comment by bioastroiner** [comment]
I never tested the mod with server since its just very hard to debug on a
dedicated server and it takes a lot of time. so its a very slow process.

@Dr-ppp 
@ananta69g 
But anyways i finally did debug it using a server and rewrote many pieces of the mod and it now works flawlessly on
a dedicated server but it still requires the ModularUI to be present on the
server tough that i will fix later, for now keep in mind that you need to have ModularUI on the server as well as it is a hard dependency. BUT the mod itself will never be Client only as there are a few stuff that i have to do over in the server in order to get data about ores accurately and then show them.

New Update will come out soon

**Comment by bioastroiner** [comment]
for the next update (1.5) I levitated the Hard dependency for ModularUI on the server so you can try and test the mod without having ModularUi present on the server at all! the thing is i could not test that unfortunently for myself so there is no guarantee it would work
