### ISSUE TITLE
Use [2.0.8-1.7.10,) instead of [2.0.8-1.7.10]

### ISSUE THREAD

**Issue by kappa-maintainer** [bioastroiner/gt6scan#4]
ModularUI has reached 2.0.9, and can't launch the game with GT6Scan

**Comment by bioastroiner** [comment]
> ModularUI has reached 2.0.9, and can't launch the game with GT6Scan

I harddepended the modularUI dependecie to only work on 2.0.8 so it will automatically crash on any other version (i hope the forge crash told you that). I did that because ModularUi API adds breaking changes to their interfaces which is not something you usualy expect from a minor version update.

So just use 2.0.8, for the next update i probably update to 2.0.9 and i will still only tagret that version until ModularUI2 devs learn about how versioning works 😅

**Comment by kappa-maintainer** [comment]
Make sense, I always doubt if gtnh guys fully follow semver
